function hostIO_rfsocChannelizer_setup(hFPGA,frameSize)
%--------------------------------------------------------------------------
% Software Interface Script Setup
% 
% Generated with MATLAB 9.10 (R2021a) and modified for the channelizer demo
%--------------------------------------------------------------------------

%% AXI4
addAXI4SlaveInterface(hFPGA, ...
	"InterfaceID", "AXI4", ...
	"BaseAddress", 0xA0000000, ...
	"AddressRange", 0x10000);

hPort_AXI4_NCO_incr = hdlcoder.DUTPort("AXI4_NCO_incr", ...
	"Direction", "IN", ...
	"DataType", numerictype(0,16,0), ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4", ...
	"IOInterfaceMapping", "0x10C");

hPort_AXI4_NCO_DAC_Ch0 = hdlcoder.DUTPort("AXI4_NCO_DAC_Ch0", ...
	"Direction", "IN", ...
	"DataType", numerictype(0,8,7), ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4", ...
	"IOInterfaceMapping", "0x110");

hPort_AXI4_PassthroughCtrl = hdlcoder.DUTPort("AXI4_PassthroughCtrl", ...
	"Direction", "IN", ...
	"DataType", numerictype('boolean'), ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4", ...
	"IOInterfaceMapping", "0x104");

hPort_TriggerCapture = hdlcoder.DUTPort("TriggerCapture", ...
	"Direction", "IN", ...
	"DataType", numerictype('boolean'), ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4", ...
	"IOInterfaceMapping", "0x100");

mapPort(hFPGA, [hPort_AXI4_NCO_incr, hPort_AXI4_NCO_DAC_Ch0, hPort_AXI4_PassthroughCtrl, hPort_TriggerCapture]);

%% AXI4-Stream DMA
addAXI4StreamInterface(hFPGA, ...
	"InterfaceID", "AXI4-Stream DMA", ...
	"WriteEnable", true, ...
	"WriteDataWidth", 64, ...
	"WriteFrameLength", frameSize, ...
	"ReadEnable", true, ...
	"ReadDataWidth", 64, ...
	"ReadFrameLength", frameSize,...
    "WriteTimeout",0,...
    "ReadTimeout",0);

hPort_MM2S_Data = hdlcoder.DUTPort("MM2S_Data", ...
	"Direction", "IN", ...
	"DataType", numerictype(0,64,0), ...
	"Dimension", [frameSize 1], ...
	"IOInterface", "AXI4-Stream DMA");

hPort_S2MM_Data = hdlcoder.DUTPort("S2MM_Data", ...
	"Direction", "OUT", ...
	"DataType", numerictype(0,64,0), ...
	"Dimension", [frameSize 1], ...
	"IOInterface", "AXI4-Stream DMA");

mapPort(hFPGA, [hPort_MM2S_Data, hPort_S2MM_Data]);

end
